name = "Matt's Portfolio Demos"
packages = ["pandas","numpy"]
[[fetch]]
from = "../assets/finance"
to_folder = "finance"
files = ["core_stuff.py","cli_app.py","Dashboard.py"]
[[fetch]]
from = "../assets/connect4"
to_folder = "connect4"
files = [""]
[[fetch]]
from = "../assets/study_stuff"
to_folder = "study_stuff"
files = [""]
[[terminal]]
auto_run = true